apiVersion: v1
kind: Pod
metadata:
  name: aide
spec:
  serviceAccountName: aide
  containers:
  - name: aide
    securityContext:
      privileged: true
      runAsUser: 0
    image: docker.io/mrogers950/aide:latest
    command: ['/scripts/aide-run.sh']
    volumeMounts:
    - mountPath: /hostroot
      name: hostroot
    - mountPath: /tmp
      name: config
    - mountPath: /scripts
      name: aide-run
  imagePullPolicy: Always
  volumes:
  - name: hostroot
    hostPath:
      path: "/"
  - name: config
    configMap:
      name: aide-conf
  - name: aide-run
    configMap:
      name: aide-run
      defaultMode: 0744

