apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2019-09-05T18:09:16Z"
  name: scc-priv
  namespace: foo
  resourceVersion: "550749"
  selfLink: /apis/rbac.authorization.k8s.io/v1/namespaces/foo/roles/scc-priv
  uid: 4647645e-d008-11e9-baf7-06053045ca2a
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - privileged
  resources:
  - securitycontextconstraints
  verbs:
  - use
